name 'java_app'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures java_app'
long_description 'Installs/Configures java_app'
version '0.1.0'

depends 'apt', '~> 2.8.2'
depends 'java', '~> 1.35.0'
depends 'maven', '~> 1.3.0'
depends 'nginx', '~> 2.7.6'
depends 'postgresql', '~> 3.4.20'
depends 'firewall', '~> 2.0.5'